# Generated by Django 5.0.7 on 2025-02-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=255)),
                ('recording_url', models.URLField()),
                ('lead_id', models.IntegerField()),
                ('uploaded', models.BooleanField(default=False)),
            ],
        ),
    ]
